import MealsData from "@/components/MealsData/MealsData";
import styles from "./styles.module.css";

export const metadata = {
  title: "meals",

  description: "Generated by create next app",
};
const page = async () => {
  return (
    <div>
      <div>
        <h1
          className={`${styles.text_red} text-center font-bold text-2xl my-20`}
        >
          {" "}
          Choose Your Meals
        </h1>
        <MealsData />
      </div>
    </div>
  );
};

export default page;
